name: Verify

on:
  push:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:

  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'oldstable', 'stable' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go vet .
      - run: go test -v -vet=off -race -shuffle ${SHUFFLE_SEED} -coverprofile=coverage.txt -covermode=atomic .
        env:
          SHUFFLE_SEED: ${{ github.run_number }}
          TEST_AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          TEST_AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
          TEST_AUTH0_DOMAIN: ${{ secrets.TEST_AUTH0_DOMAIN }}
      - uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
          fail_ci_if_error: true
